version: "3.8"

services:
    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        container_name: postgres
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/docker/_db:/var/lib/postgresql/data

    app:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - postgres

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./storage/docker/logs/nginx:/var/log/nginx/
            - ./:/var/www
